language: php
php:
  - 7.3
install:
  - travis_retry composer install --no-interaction --no-suggest
script:
  - composer lint
  - composer test -- --coverage-clover=coverage.xml
after_success:
  - bash <(curl -s https://codecov.io/bash)
